import { ArrowRight, AudioLines, Check, Globe2, Headphones, Play, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api, formatTime, Product, User, Wallet } from "./api";
import { AuthDialog } from "./AuthDialog";
import { Interpreter } from "./Interpreter";

type Locale="ja"|"en"|"zh-CN"; type View="home"|"account";
const copy={
  ja:{how:"使い方",price:"料金",faq:"よくある質問",login:"ログイン",account:"マイページ",cta:"15分無料で試す",eyebrow:"声が届けば、心も届く。",hero:"話した言葉を、\nそのまま世界へ。",lead:"マイクに話すだけ。低遅延のAI音声通訳が、あなたの声を別の言語へ届けます。字幕を読む必要はありません。",demo:"実際の通訳を見る",trial:"登録後15分無料",card:"ブラウザで今すぐ通訳",from:"入力言語",to:"出力言語",start:"無料で始める",why:"伝えたい瞬間を、待たせない。",pricing:"必要な時間だけ購入",notice:"音声と翻訳内容は原則保存しません。"},
  en:{how:"How it works",price:"Pricing",faq:"FAQ",login:"Sign in",account:"My account",cta:"Try 15 minutes free",eyebrow:"When your voice reaches them, your heart can too.",hero:"Speak naturally.\nBe heard worldwide.",lead:"Just speak into your microphone. Low-latency AI interpretation carries your voice into another language—no subtitles to follow.",demo:"Watch a real demo",trial:"15 free minutes after signup",card:"Interpret now in your browser",from:"Input language",to:"Output language",start:"Start for free",why:"Keep the moment moving.",pricing:"Buy only the time you need",notice:"We do not normally store audio or translated content."},
  "zh-CN":{how:"使用方法",price:"价格",faq:"常见问题",login:"登录",account:"我的账户",cta:"免费试用15分钟",eyebrow:"声音传达，心意也能传达。",hero:"自然说话，\n让世界听见。",lead:"只需对着麦克风说话。低延迟AI语音口译会将您的声音转换成另一种语言，无需阅读字幕。",demo:"观看真实演示",trial:"注册后免费15分钟",card:"立即在浏览器中口译",from:"输入语言",to:"输出语言",start:"免费开始",why:"让沟通无需等待。",pricing:"只购买需要的时间",notice:"原则上不保存音频或翻译内容。"}
} as const;
const fallbackProducts=[{id:'00000000-0000-4000-8000-000000000060',code:'starter_60',name_key:'Starter',seconds_granted:3600,price_minor:1500,currency:'JPY'},{id:'00000000-0000-4000-8000-000000000300',code:'standard_300',name_key:'Standard',seconds_granted:18000,price_minor:5500,currency:'JPY'},{id:'00000000-0000-4000-8000-000000001000',code:'event_1000',name_key:'Event',seconds_granted:60000,price_minor:15000,currency:'JPY'}];

export function App(){
  const [locale,setLocale]=useState<Locale>((localStorage.getItem('swli.locale') as Locale)||'ja');const [view,setView]=useState<View>('home');const [auth,setAuth]=useState<"login"|"register"|null>(null);const [user,setUser]=useState<User|null>(null);const [wallet,setWallet]=useState<Wallet>({trial_seconds:0,paid_seconds:0,reserved_seconds:0});const [csrf,setCsrf]=useState('');const [products,setProducts]=useState<Product[]>(fallbackProducts);const [flash,setFlash]=useState('');const t=copy[locale];const heroLines=useMemo(()=>t.hero.split('\n'),[t.hero]);
  useEffect(()=>{localStorage.setItem('swli.locale',locale)},[locale]);
  useEffect(()=>{refreshAccount();api<{products:Product[]}>('products.php').then(r=>setProducts(r.products)).catch(()=>{});const token=new URLSearchParams(location.search).get('token');if(location.pathname.includes('verify-email')&&token){api('auth/verify-email.php',{method:'POST',body:JSON.stringify({token})}).then(()=>{history.replaceState({},'', '/');setFlash('メール確認が完了しました。15分の無料時間を付与しました。');setAuth('login')}).catch(e=>setFlash(e.message))}},[]);
  async function refreshAccount(){try{const result=await api<{user:User;wallet:Wallet;csrf_token:string}>('auth/me.php');setUser(result.user);setWallet(result.wallet);setCsrf(result.csrf_token)}catch{setUser(null)}}
  function openAccount(){if(!user)setAuth('login');else setView('account')}
  async function checkout(product:Product){if(!user){setAuth('register');return}try{const result=await api<{checkout_url:string}>('checkout/create.php',{method:'POST',body:JSON.stringify({product_id:product.id})},csrf);location.href=result.checkout_url}catch(e){setFlash(e instanceof Error?e.message:'決済を開始できませんでした。')}}
  async function logout(){await api('auth/logout.php',{method:'POST'},csrf).catch(()=>{});setUser(null);setView('home')}
  const total=Number(wallet.trial_seconds)+Number(wallet.paid_seconds);
  return <div className="site">
    <header><button className="brand brand-button" onClick={()=>setView('home')}><span className="brand-mark"><AudioLines size={22}/></span><span>ShalomWorks <b>Live Interpreter</b></span></button><nav><a href="#how" onClick={()=>setView('home')}>{t.how}</a><a href="#pricing" onClick={()=>setView('home')}>{t.price}</a><a href="#faq" onClick={()=>setView('home')}>{t.faq}</a></nav><div className="header-actions"><label className="locale"><Globe2 size={16}/><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="ja">日本語</option><option value="en">English</option><option value="zh-CN">简体中文</option></select></label><button className="link-button" onClick={openAccount}>{user?t.account:t.login}</button><button className="primary small" onClick={()=>user?setView('account'):setAuth('register')}>{user?formatTime(total):t.cta}</button></div></header>
    {flash&&<div className="flash" onClick={()=>setFlash('')}>{flash}<button>×</button></div>}
    {view==='account'&&user?<main className="account-page"><section className="account-summary"><div><p className="section-kicker">MY ACCOUNT</p><h1>こんにちは{user.display_name?`、${user.display_name}`:''}</h1><p>{user.email}</p></div><div className="balance-card"><span>残り通訳時間</span><strong>{formatTime(total)}</strong><small>無料 {formatTime(Number(wallet.trial_seconds))} ／ 有料 {formatTime(Number(wallet.paid_seconds))}</small></div></section><Interpreter wallet={wallet} csrf={csrf} onBalance={seconds=>setWallet(w=>({...w,trial_seconds:Math.min(Number(w.trial_seconds),seconds),paid_seconds:Math.max(0,seconds-Math.min(Number(w.trial_seconds),seconds))}))}/><section className="account-products"><h2>通訳時間を追加</h2><ProductCards products={products} onChoose={checkout}/></section><div className="account-actions"><button className="link-button" onClick={logout}>ログアウト</button></div></main>:<main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={16}/>{t.eyebrow}</p><h1>{heroLines.map((line,i)=><span key={line}>{line}{i===0&&<br/>}</span>)}</h1><p className="lead">{t.lead}</p><div className="hero-actions"><button className="primary" onClick={()=>setAuth('register')}>{t.cta}<ArrowRight size={19}/></button><button className="secondary" onClick={()=>document.getElementById('demo')?.scrollIntoView({behavior:'smooth'})}><Play size={17}/>{t.demo}</button></div><p className="trial"><Check size={16}/>{t.trial}<span>•</span><ShieldCheck size={16}/>{t.notice}</p></div><div className="interpreter-card"><div className="card-top"><div><span className="live-dot"/> LIVE INTERPRETER</div><span className="balance">15:00 FREE</span></div><h2>{t.card}</h2><div className="language-row"><label>{t.from}<select><option>日本語</option><option>English</option><option>中文</option></select></label><span className="swap">→</span><label>{t.to}<select><option>English</option><option>日本語</option><option>中文</option></select></label></div><div className="wave" aria-label="microphone level">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${16+((i*17)%48)}px`}}/>)}</div><button className="start" onClick={()=>setAuth('register')}><span className="mic">●</span>{t.start}</button><p><Headphones size={15}/> Headphones recommended</p></div></section>
      <section className="trust"><span>FOR CHURCHES</span><span>EVENTS</span><span>EDUCATION</span><span>TRAVEL</span><span>CUSTOMER SUPPORT</span></section>
      <section id="demo" className="demo-section"><div className="demo-placeholder"><Play size={42}/><strong>Real-time interpretation demo</strong><span>実演動画を公開前に配置します</span></div><div><p className="section-kicker">SEE IT IN ACTION</p><h2>話し続けても、通訳は止まりません。</h2><p>実際の日本語音声が低遅延で英語音声へ変わる様子を、公開前の実演収録で掲載します。</p></div></section>
      <section id="how" className="section"><p className="section-kicker">WHY LIVE INTERPRETER</p><h2>{t.why}</h2><div className="features"><article><b>01</b><h3>Speak</h3><p>マイクと入力言語を選び、自然に話します。</p></article><article><b>02</b><h3>Interpret</h3><p>AIが音声を途切れにくく低遅延で通訳します。</p></article><article><b>03</b><h3>Listen</h3><p>聞き手は選択した言語の自然な音声を聞きます。</p></article></div></section>
      <section id="pricing" className="section pricing"><p className="section-kicker">SIMPLE PRICING</p><h2>{t.pricing}</h2><ProductCards products={products} onChoose={checkout}/><p className="pricing-note">初回登録は15分無料。購入時間は秒単位で消費されます。</p></section>
      <section id="faq" className="section faq"><p className="section-kicker">FAQ</p><h2>よくある質問</h2><details><summary>会話は保存されますか？</summary><p>音声、翻訳音声、翻訳本文は原則として保存しません。利用時間や言語ペアなどの運用情報だけを保存します。</p></details><details><summary>残高がなくなるとどうなりますか？</summary><p>通訳中継サーバーが残高を確認し、0秒になった時点で自動的に終了します。</p></details><details><summary>どの端末で使えますか？</summary><p>マイクが利用できる主要なPC・スマートフォンブラウザに対応します。</p></details></section>
    </main>}
    <footer><span>© 2026 ShalomWorks</span><span><a href="/terms">利用規約</a> · <a href="/privacy">プライバシー</a> · <a href="/commercial-disclosure">特定商取引法に基づく表記</a></span></footer>{auth&&<AuthDialog mode={auth} onClose={()=>setAuth(null)} onSignedIn={refreshAccount} locale={locale}/>}</div>
}

function ProductCards({products,onChoose}:{products:Product[];onChoose:(product:Product)=>void}){return <div className="plans">{products.map((product,index)=><article className={index===1?'popular':''} key={product.id}>{index===1&&<span className="badge">MOST POPULAR</span>}<h3>{product.code.startsWith('starter')?'Starter':product.code.startsWith('standard')?'Standard':'Event'}</h3><strong>¥{Number(product.price_minor).toLocaleString()}</strong><p>{Math.round(Number(product.seconds_granted)/60).toLocaleString()} minutes</p><button className={index===1?'primary':'secondary'} onClick={()=>onChoose(product)}>このプランを選ぶ</button></article>)}</div>}
