import { useEffect, useRef, useState } from "react";
import { Headphones, Mic, Square, Volume2 } from "lucide-react";
import { api, formatTime, Wallet } from "./api";

const languages=[['ja','日本語'],['en','English'],['zh','中文'],['ko','한국어'],['es','Español'],['fr','Français'],['de','Deutsch'],['pt','Português'],['it','Italiano'],['ru','Русский'],['ar','العربية'],['hi','हिन्दी'],['th','ไทย'],['vi','Tiếng Việt']];
function toBase64(bytes:Uint8Array){let s="";for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)}
function pcm16(samples:Float32Array,inputRate:number){const ratio=inputRate/24000;const length=Math.floor(samples.length/ratio);const output=new Int16Array(length);for(let i=0;i<length;i++){const sample=Math.max(-1,Math.min(1,samples[Math.floor(i*ratio)]));output[i]=sample<0?sample*0x8000:sample*0x7fff}return toBase64(new Uint8Array(output.buffer))}

export function Interpreter({wallet,csrf,onBalance}:{wallet:Wallet;csrf:string;onBalance:(seconds:number)=>void}){
  const [source,setSource]=useState('ja'),[target,setTarget]=useState('en'),[status,setStatus]=useState('idle'),[level,setLevel]=useState(0),[remaining,setRemaining]=useState(Number(wallet.trial_seconds)+Number(wallet.paid_seconds)),[volume,setVolume]=useState(.85),[message,setMessage]=useState('');
  const stream=useRef<MediaStream|null>(null); const context=useRef<AudioContext|null>(null); const processor=useRef<ScriptProcessorNode|null>(null); const socket=useRef<WebSocket|null>(null); const analyserFrame=useRef<number|null>(null); const playCursor=useRef(0);
  useEffect(()=>{setRemaining(Number(wallet.trial_seconds)+Number(wallet.paid_seconds))},[wallet]);
  useEffect(()=>()=>shutdown(true),[]);
  async function prepare(){if(stream.current)return;const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=media;const ctx=new AudioContext();context.current=ctx;playCursor.current=ctx.currentTime;const sourceNode=ctx.createMediaStreamSource(media);const analyser=ctx.createAnalyser();analyser.fftSize=256;sourceNode.connect(analyser);const values=new Uint8Array(analyser.frequencyBinCount);const draw=()=>{analyser.getByteFrequencyData(values);setLevel(Math.min(100,Math.round(values.reduce((a,b)=>a+b,0)/values.length/1.25)));analyserFrame.current=requestAnimationFrame(draw)};draw();}
  function play(delta:string){const ctx=context.current;if(!ctx)return;const raw=atob(delta);const input=new Int16Array(raw.length/2);for(let i=0;i<input.length;i++)input[i]=(raw.charCodeAt(i*2)|(raw.charCodeAt(i*2+1)<<8))<<16>>16;const buffer=ctx.createBuffer(1,input.length,24000);const channel=buffer.getChannelData(0);for(let i=0;i<input.length;i++)channel[i]=input[i]/32768;const node=ctx.createBufferSource();const gain=ctx.createGain();gain.gain.value=volume;node.buffer=buffer;node.connect(gain).connect(ctx.destination);playCursor.current=Math.max(playCursor.current,ctx.currentTime+.03);node.start(playCursor.current);playCursor.current+=buffer.duration;}
  async function start(){setMessage('');try{await prepare();if(source===target)throw new Error('入力言語と出力言語を別にしてください。');const authorization=await api<{gateway_url:string;access_token:string;available_seconds:number}>("interpreter/authorize.php",{method:'POST',body:JSON.stringify({source_language:source,target_language:target})},csrf);const ws=new WebSocket(authorization.gateway_url.replace(/^http/,'ws')+'/translate');socket.current=ws;ws.onopen=()=>ws.send(JSON.stringify({type:'authenticate',access_token:authorization.access_token}));ws.onmessage=(event)=>{const data=JSON.parse(event.data);if(data.type==='ready'){setStatus('live');const ctx=context.current!;const src=ctx.createMediaStreamSource(stream.current!);const proc=ctx.createScriptProcessor(4096,1,1);processor.current=proc;proc.onaudioprocess=e=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'audio',audio:pcm16(e.inputBuffer.getChannelData(0),ctx.sampleRate)}))};src.connect(proc);proc.connect(ctx.destination)}if(data.type==='audio')play(data.delta);if(data.type==='billing'){setRemaining(data.remaining_seconds);onBalance(data.remaining_seconds)}};ws.onclose=(event)=>{setStatus('idle');processor.current?.disconnect();processor.current=null;if(event.code!==1000)setMessage(event.reason==='balance_exhausted'?'通訳時間を使い切りました。':'通訳接続が終了しました。')}}catch(error){setStatus('idle');setMessage(error instanceof Error?error.message:'開始できませんでした。')}}
  function stop(){socket.current?.send(JSON.stringify({type:'stop'}));setStatus('stopping')}
  function shutdown(stopTracks=true){socket.current?.close();processor.current?.disconnect();if(analyserFrame.current!==null)cancelAnimationFrame(analyserFrame.current);if(stopTracks)stream.current?.getTracks().forEach(t=>t.stop());context.current?.close();stream.current=null;context.current=null;processor.current=null;socket.current=null}
  async function testSound(){await prepare();const ctx=context.current!;const oscillator=ctx.createOscillator();const gain=ctx.createGain();oscillator.frequency.value=440;gain.gain.value=.12*volume;oscillator.connect(gain).connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+1.2)}
  return <section className="interpreter-app"><div className="app-heading"><div><p className="section-kicker">LIVE INTERPRETER</p><h2>リアルタイム音声通訳</h2></div><div className="wallet-pill">残り <strong>{formatTime(remaining)}</strong></div></div><div className="language-row app-languages"><label>入力言語<select value={source} onChange={e=>setSource(e.target.value)} disabled={status!=='idle'}>{languages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><span className="swap">→</span><label>出力言語<select value={target} onChange={e=>setTarget(e.target.value)} disabled={status!=='idle'}>{languages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><div className="meter"><div style={{width:`${level}%`}}/><span><Mic size={16}/> INPUT {level}%</span></div><div className="audio-controls"><button className="secondary" onClick={prepare}><Mic size={17}/>マイクを有効化</button><button className="secondary" onClick={testSound}><Volume2 size={17}/>出力音量テスト</button><label><Volume2 size={16}/><input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label></div>{status==='idle'?<button className="primary interpreter-start" onClick={start} disabled={remaining<=0}><Mic/>通訳を開始</button>:<button className="stop-button" onClick={stop} disabled={status==='stopping'}><Square/> {status==='stopping'?'終了処理中…':'通訳を終了'}</button>}<p className={`status-line ${status}`}>{status==='live'?'● 通訳中 — 話し続けてください':'○ 待機中'} <span><Headphones size={15}/>イヤホン推奨</span></p>{message&&<p className="form-message">{message}</p>}</section>
}
