import type { Locale } from "./locales";

export const siteCopyExtra: Partial<Record<Locale, Record<string, string>>> = {
  es: {
    how: "Cómo funciona",
    price: "Precios",
    faq: "Preguntas frecuentes",
    login: "Iniciar sesión",
    account: "Mi cuenta",
    cta: "Probar 1 minuto gratis",
    eyebrow: "Cuando llega tu voz, también llega tu intención.",
    hero: "Habla con naturalidad.\nQue te escuche el mundo.",
    lead: "Habla al micrófono. La interpretación por IA de baja latencia transmite tu voz en otro idioma con audio y subtítulos.",
    demo: "Ver demostración",
    demoPlaceholder: "Una voz que llega al mundo",
    demoTitle: "La voz se convierte en luz y viaja por el mundo.",
    demoText:
      "Una historia visual sin idioma: una voz se interpreta y llega a personas de todo el mundo en el mismo instante.",
    demoVisualLabel:
      "Animación de voces en muchos idiomas que se convierten en luz y llegan a oyentes de todo el mundo",
    demoSound: "Reproducir sonido",
    visionText:
      "Voces diferentes, una misma humanidad. Un futuro donde todas las personas puedan ser comprendidas.",
    trial: "1 minuto gratis tras registrarte",
    card: "Interpreta ahora en el navegador",
    from: "Idioma de entrada",
    to: "Idioma de salida",
    start: "Empezar gratis",
    why: "Comunícate sin hacer esperar.",
    pricing: "Planes mensuales y créditos extra",
    greeting: "Hola",
    remaining: "Saldo de créditos LI",
    addTime: "Añadir créditos",
    logout: "Cerrar sesión",
    subscriptionHeading: "Planes mensuales",
    topupHeading: "Créditos extra",
    monthly: "mes",
    credits: "Créditos LI",
    choose: "Elegir este plan",
    faqTitle: "Preguntas frecuentes",
  },
  pt: {
    how: "Como funciona",
    price: "Preços",
    faq: "Perguntas frequentes",
    login: "Entrar",
    account: "Minha conta",
    cta: "Testar 1 minuto grátis",
    eyebrow: "Quando sua voz chega, sua intenção também chega.",
    hero: "Fale naturalmente.\nSeja ouvido no mundo.",
    lead: "Fale ao microfone. A interpretação por IA de baixa latência entrega sua voz em outro idioma com áudio e legendas.",
    demo: "Ver demonstração",
    demoPlaceholder: "Uma voz alcançando o mundo",
    demoTitle: "A voz vira luz e percorre o mundo.",
    demoText:
      "Uma história visual sem idioma: uma voz é interpretada e chega a pessoas em todo o mundo ao mesmo tempo.",
    demoVisualLabel:
      "Animação de vozes em vários idiomas virando luz e chegando a ouvintes no mundo todo",
    demoSound: "Ouvir o som",
    visionText:
      "Vozes diferentes, a mesma humanidade. Um futuro em que todas as pessoas possam ser compreendidas.",
    trial: "1 minuto grátis após o cadastro",
    card: "Interpretar agora no navegador",
    from: "Idioma de entrada",
    to: "Idioma de saída",
    start: "Começar grátis",
    why: "Comunique-se sem esperar.",
    pricing: "Planos mensais e créditos extras",
    greeting: "Olá",
    remaining: "Saldo de créditos LI",
    addTime: "Adicionar créditos",
    logout: "Sair",
    subscriptionHeading: "Planos mensais",
    topupHeading: "Créditos extras",
    monthly: "mês",
    credits: "Créditos LI",
    choose: "Escolher este plano",
    faqTitle: "Perguntas frequentes",
  },
  fr: {
    how: "Fonctionnement",
    price: "Tarifs",
    faq: "FAQ",
    login: "Connexion",
    account: "Mon compte",
    cta: "Essayer 1 minute gratuitement",
    eyebrow: "Quand votre voix arrive, votre intention aussi.",
    hero: "Parlez naturellement.\nSoyez entendu partout.",
    lead: "Parlez dans votre micro. L’interprétation IA à faible latence transmet votre voix dans une autre langue avec audio et sous-titres.",
    demo: "Voir la démonstration",
    demoPlaceholder: "Une voix qui atteint le monde",
    demoTitle: "La voix devient lumière et parcourt le monde.",
    demoText:
      "Une histoire visuelle sans langue imposée : une voix est interprétée et atteint partout les personnes au même instant.",
    demoVisualLabel:
      "Animation de voix de plusieurs langues devenant lumière et atteignant des auditeurs partout dans le monde",
    demoSound: "Écouter le son",
    visionText:
      "Des voix différentes, une même humanité. Un avenir où chaque personne peut être comprise.",
    trial: "1 minute gratuite après inscription",
    card: "Interprétez dans votre navigateur",
    from: "Langue d’entrée",
    to: "Langue de sortie",
    start: "Commencer gratuitement",
    why: "Communiquez sans attendre.",
    pricing: "Forfaits mensuels et crédits supplémentaires",
    greeting: "Bonjour",
    remaining: "Solde de crédits LI",
    addTime: "Ajouter des crédits",
    logout: "Déconnexion",
    subscriptionHeading: "Forfaits mensuels",
    topupHeading: "Crédits supplémentaires",
    monthly: "mois",
    credits: "Crédits LI",
    choose: "Choisir ce forfait",
    faqTitle: "Questions fréquentes",
  },
  de: {
    how: "So funktioniert es",
    price: "Preise",
    faq: "FAQ",
    login: "Anmelden",
    account: "Mein Konto",
    cta: "1 Minute kostenlos testen",
    eyebrow: "Wenn Ihre Stimme ankommt, kommt auch Ihre Botschaft an.",
    hero: "Natürlich sprechen.\nWeltweit verstanden werden.",
    lead: "Sprechen Sie ins Mikrofon. KI-Dolmetschen mit geringer Latenz überträgt Ihre Stimme mit Audio und Untertiteln in eine andere Sprache.",
    demo: "Demo ansehen",
    demoPlaceholder: "Eine Stimme erreicht die Welt",
    demoTitle: "Eine Stimme wird zu Licht und reist um die Welt.",
    demoText:
      "Eine sprachneutrale visuelle Geschichte: Eine Stimme wird gedolmetscht und erreicht Menschen überall im selben Moment.",
    demoVisualLabel:
      "Animation, in der Stimmen vieler Sprachen zu Licht werden und Menschen auf der ganzen Welt erreichen",
    demoSound: "Klang abspielen",
    visionText:
      "Verschiedene Stimmen, eine gemeinsame Menschlichkeit. Eine Zukunft, in der alle verstanden werden.",
    trial: "1 kostenlose Minute nach Registrierung",
    card: "Jetzt im Browser dolmetschen",
    from: "Eingabesprache",
    to: "Ausgabesprache",
    start: "Kostenlos starten",
    why: "Kommunikation ohne Wartezeit.",
    pricing: "Monatspläne und Zusatzguthaben",
    greeting: "Willkommen",
    remaining: "LI-Guthaben",
    addTime: "Guthaben hinzufügen",
    logout: "Abmelden",
    subscriptionHeading: "Monatspläne",
    topupHeading: "Zusatzguthaben",
    monthly: "Monat",
    credits: "LI-Credits",
    choose: "Plan wählen",
    faqTitle: "Häufige Fragen",
  },
  ru: {
    how: "Как это работает",
    price: "Тарифы",
    faq: "Вопросы",
    login: "Войти",
    account: "Мой аккаунт",
    cta: "Попробовать 1 минуту бесплатно",
    eyebrow: "Когда слышен голос, понятны и намерения.",
    hero: "Говорите естественно.\nБудьте услышаны во всём мире.",
    lead: "Говорите в микрофон. ИИ-перевод с низкой задержкой передаёт ваш голос на другом языке со звуком и субтитрами.",
    demo: "Смотреть демонстрацию",
    demoPlaceholder: "Один голос достигает мира",
    demoTitle: "Голос становится светом и облетает мир.",
    demoText:
      "Визуальная история без привязки к языку: голос переводится и одновременно достигает людей по всему миру.",
    demoVisualLabel:
      "Анимация, где голоса на разных языках становятся светом и достигают слушателей по всему миру",
    demoSound: "Включить звук",
    visionText:
      "Разные голоса, единое человечество. Будущее, в котором каждого могут понять.",
    trial: "1 бесплатная минута после регистрации",
    card: "Переводите прямо в браузере",
    from: "Язык ввода",
    to: "Язык вывода",
    start: "Начать бесплатно",
    why: "Общение без ожидания.",
    pricing: "Ежемесячные планы и дополнительные кредиты",
    greeting: "Здравствуйте",
    remaining: "Баланс LI-кредитов",
    addTime: "Добавить кредиты",
    logout: "Выйти",
    subscriptionHeading: "Ежемесячные планы",
    topupHeading: "Дополнительные кредиты",
    monthly: "месяц",
    credits: "LI-кредиты",
    choose: "Выбрать план",
    faqTitle: "Частые вопросы",
  },
  ko: {
    how: "사용 방법",
    price: "요금",
    faq: "자주 묻는 질문",
    login: "로그인",
    account: "내 계정",
    cta: "1분 무료 체험",
    eyebrow: "목소리가 닿으면 마음도 전해집니다.",
    hero: "자연스럽게 말하세요.\n세계가 들을 수 있게.",
    lead: "마이크에 말하기만 하세요. 저지연 AI 통역이 음성과 자막으로 다른 언어에 목소리를 전달합니다.",
    demo: "데모 보기",
    demoPlaceholder: "하나의 목소리가 세계로",
    demoTitle: "목소리가 빛이 되어 세계로 퍼집니다.",
    demoText:
      "특정 언어에 의존하지 않는 시각적 이야기입니다. 한 목소리가 통역되어 전 세계 사람들에게 동시에 전달됩니다.",
    demoVisualLabel:
      "여러 언어의 목소리가 빛이 되어 전 세계 청중에게 전달되는 애니메이션",
    demoSound: "사운드 듣기",
    visionText:
      "서로 다른 목소리, 하나의 인류. 누구나 이해받을 수 있는 미래를 향해.",
    trial: "가입 후 1분 무료",
    card: "브라우저에서 바로 통역",
    from: "입력 언어",
    to: "출력 언어",
    start: "무료로 시작",
    why: "기다림 없는 소통.",
    pricing: "월간 플랜과 추가 크레딧",
    greeting: "안녕하세요",
    remaining: "LI 크레딧 잔액",
    addTime: "크레딧 추가",
    logout: "로그아웃",
    subscriptionHeading: "월간 플랜",
    topupHeading: "추가 크레딧",
    monthly: "월",
    credits: "LI 크레딧",
    choose: "이 플랜 선택",
    faqTitle: "자주 묻는 질문",
  },
  hi: {
    how: "कैसे काम करता है",
    price: "मूल्य",
    faq: "सामान्य प्रश्न",
    login: "लॉग इन",
    account: "मेरा खाता",
    cta: "1 मिनट निःशुल्क आज़माएँ",
    eyebrow: "आवाज़ पहुँचे तो भावना भी पहुँचती है।",
    hero: "स्वाभाविक रूप से बोलें।\nदुनिया भर में सुने जाएँ।",
    lead: "माइक्रोफ़ोन में बोलें। कम विलंब वाला AI दुभाषिया आपकी आवाज़ को ऑडियो और उपशीर्षक के साथ दूसरी भाषा में पहुँचाता है।",
    demo: "डेमो देखें",
    demoPlaceholder: "एक आवाज़, पूरी दुनिया तक",
    demoTitle: "आवाज़ रोशनी बनकर दुनिया भर में पहुँचती है।",
    demoText:
      "भाषा से परे एक दृश्य कहानी: एक आवाज़ का अनुवाद होकर वह एक ही पल में दुनिया भर के लोगों तक पहुँचती है।",
    demoVisualLabel:
      "कई भाषाओं की आवाज़ों के रोशनी बनकर दुनिया भर के श्रोताओं तक पहुँचने का एनिमेशन",
    demoSound: "ध्वनि चलाएँ",
    visionText:
      "अलग आवाज़ें, साझा मानवता। एक ऐसा भविष्य जहाँ हर व्यक्ति को समझा जा सके।",
    trial: "पंजीकरण के बाद 1 मिनट निःशुल्क",
    card: "ब्राउज़र में अभी अनुवाद करें",
    from: "इनपुट भाषा",
    to: "आउटपुट भाषा",
    start: "निःशुल्क शुरू करें",
    why: "बिना प्रतीक्षा संवाद करें।",
    pricing: "मासिक योजनाएँ और अतिरिक्त क्रेडिट",
    greeting: "नमस्ते",
    remaining: "LI क्रेडिट शेष",
    addTime: "क्रेडिट जोड़ें",
    logout: "लॉग आउट",
    subscriptionHeading: "मासिक योजनाएँ",
    topupHeading: "अतिरिक्त क्रेडिट",
    monthly: "माह",
    credits: "LI क्रेडिट",
    choose: "यह योजना चुनें",
    faqTitle: "सामान्य प्रश्न",
  },
  id: {
    how: "Cara kerja",
    price: "Harga",
    faq: "Tanya jawab",
    login: "Masuk",
    account: "Akun saya",
    cta: "Coba gratis 1 menit",
    eyebrow: "Saat suara tersampaikan, maksud pun tersampaikan.",
    hero: "Bicara dengan alami.\nDidengar di seluruh dunia.",
    lead: "Cukup bicara ke mikrofon. Interpretasi AI berlatensi rendah menyampaikan suara Anda dalam bahasa lain dengan audio dan teks.",
    demo: "Lihat demo",
    demoPlaceholder: "Satu suara menjangkau dunia",
    demoTitle: "Suara menjadi cahaya dan menjelajah dunia.",
    demoText:
      "Kisah visual tanpa bergantung pada bahasa: satu suara diterjemahkan dan mencapai orang di seluruh dunia pada saat yang sama.",
    demoVisualLabel:
      "Animasi suara berbagai bahasa menjadi cahaya dan mencapai pendengar di seluruh dunia",
    demoSound: "Putar suara",
    visionText:
      "Suara yang berbeda, kemanusiaan yang sama. Masa depan ketika setiap orang dapat dipahami.",
    trial: "Gratis 1 menit setelah mendaftar",
    card: "Interpretasi sekarang di browser",
    from: "Bahasa masukan",
    to: "Bahasa keluaran",
    start: "Mulai gratis",
    why: "Berkomunikasi tanpa menunggu.",
    pricing: "Paket bulanan dan kredit tambahan",
    greeting: "Halo",
    remaining: "Saldo kredit LI",
    addTime: "Tambah kredit",
    logout: "Keluar",
    subscriptionHeading: "Paket bulanan",
    topupHeading: "Kredit tambahan",
    monthly: "bulan",
    credits: "Kredit LI",
    choose: "Pilih paket",
    faqTitle: "Pertanyaan umum",
  },
  vi: {
    how: "Cách hoạt động",
    price: "Bảng giá",
    faq: "Câu hỏi thường gặp",
    login: "Đăng nhập",
    account: "Tài khoản",
    cta: "Dùng thử miễn phí 1 phút",
    eyebrow: "Khi tiếng nói được truyền đi, tấm lòng cũng được truyền đạt.",
    hero: "Nói tự nhiên.\nĐược lắng nghe khắp thế giới.",
    lead: "Chỉ cần nói vào micrô. Phiên dịch AI độ trễ thấp truyền giọng nói của bạn sang ngôn ngữ khác bằng âm thanh và phụ đề.",
    demo: "Xem bản demo",
    demoPlaceholder: "Một giọng nói vươn ra thế giới",
    demoTitle: "Giọng nói hóa thành ánh sáng và lan khắp thế giới.",
    demoText:
      "Một câu chuyện hình ảnh không phụ thuộc ngôn ngữ: giọng nói được phiên dịch và đến với mọi người trên khắp thế giới cùng một lúc.",
    demoVisualLabel:
      "Hoạt ảnh các giọng nói đa ngôn ngữ hóa thành ánh sáng và đến với người nghe khắp thế giới",
    demoSound: "Phát âm thanh",
    visionText:
      "Những tiếng nói khác nhau, một nhân loại chung. Một tương lai nơi mọi người đều được thấu hiểu.",
    trial: "Miễn phí 1 phút sau khi đăng ký",
    card: "Phiên dịch ngay trong trình duyệt",
    from: "Ngôn ngữ đầu vào",
    to: "Ngôn ngữ đầu ra",
    start: "Bắt đầu miễn phí",
    why: "Giao tiếp không phải chờ đợi.",
    pricing: "Gói tháng và tín dụng bổ sung",
    greeting: "Xin chào",
    remaining: "Số dư tín dụng LI",
    addTime: "Thêm tín dụng",
    logout: "Đăng xuất",
    subscriptionHeading: "Gói hàng tháng",
    topupHeading: "Tín dụng bổ sung",
    monthly: "tháng",
    credits: "Tín dụng LI",
    choose: "Chọn gói này",
    faqTitle: "Câu hỏi thường gặp",
  },
  it: {
    how: "Come funziona",
    price: "Prezzi",
    faq: "Domande frequenti",
    login: "Accedi",
    account: "Il mio account",
    cta: "Prova 1 minuto gratis",
    eyebrow: "Quando arriva la voce, arriva anche l’intenzione.",
    hero: "Parla naturalmente.\nFatti ascoltare nel mondo.",
    lead: "Parla nel microfono. L’interpretazione AI a bassa latenza trasmette la tua voce in un’altra lingua con audio e sottotitoli.",
    demo: "Guarda la demo",
    demoPlaceholder: "Una voce raggiunge il mondo",
    demoTitle: "La voce diventa luce e attraversa il mondo.",
    demoText:
      "Una storia visiva senza una lingua specifica: una voce viene interpretata e raggiunge persone ovunque nello stesso momento.",
    demoVisualLabel:
      "Animazione di voci in molte lingue che diventano luce e raggiungono ascoltatori in tutto il mondo",
    demoSound: "Riproduci il suono",
    visionText:
      "Voci diverse, la stessa umanità. Un futuro in cui ogni persona possa essere compresa.",
    trial: "1 minuto gratis dopo la registrazione",
    card: "Interpreta ora nel browser",
    from: "Lingua di input",
    to: "Lingua di output",
    start: "Inizia gratis",
    why: "Comunicare senza attese.",
    pricing: "Piani mensili e crediti extra",
    greeting: "Ciao",
    remaining: "Saldo crediti LI",
    addTime: "Aggiungi crediti",
    logout: "Esci",
    subscriptionHeading: "Piani mensili",
    topupHeading: "Crediti extra",
    monthly: "mese",
    credits: "Crediti LI",
    choose: "Scegli questo piano",
    faqTitle: "Domande frequenti",
  },
};
