<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require_once dirname(__DIR__).'/lib/stripe.php';require_method('POST');$admin=require_admin($config);require_csrf();$body=json_body();
$paymentId=(string)($body['payment_id']??'');$requested=filter_var($body['amount_minor']??null,FILTER_VALIDATE_INT);$reason=trim((string)($body['reason']??''));
if(!preg_match('/^[a-f0-9-]{36}$/',$paymentId)||($requested!==false&&$requested!==null&&$requested<=0)||mb_strlen($reason)<5||mb_strlen($reason)>200)json_error('VALIDATION_ERROR','Refund request is invalid.');
$pdo=db($config);$requestId=uuid_v4();
try{$pdo->beginTransaction();$stmt=$pdo->prepare("SELECT id,amount_minor,refunded_minor,stripe_payment_intent_id,status FROM payments WHERE id=? FOR UPDATE");$stmt->execute([$paymentId]);$payment=$stmt->fetch();if(!$payment||!in_array($payment['status'],['paid','refunded'],true)||!$payment['stripe_payment_intent_id'])throw new RuntimeException('PAYMENT_NOT_REFUNDABLE');$stmt=$pdo->prepare("SELECT COALESCE(SUM(amount_minor),0) FROM refund_requests WHERE payment_id=? AND status IN ('pending','submitted')");$stmt->execute([$paymentId]);$reserved=(int)$stmt->fetchColumn();$available=(int)$payment['amount_minor']-(int)$payment['refunded_minor']-$reserved;$amount=($requested===false||$requested===null)?$available:(int)$requested;if($amount<=0||$amount>$available)throw new RuntimeException('REFUND_AMOUNT_INVALID');$pdo->prepare("INSERT INTO refund_requests (id,payment_id,admin_user_id,amount_minor,reason) VALUES (?,?,?,?,?)")->execute([$requestId,$paymentId,$admin['id'],$amount,$reason]);$pdo->commit();
  try{$refund=stripe_request($config,'POST','/v1/refunds',['payment_intent'=>$payment['stripe_payment_intent_id'],'amount'=>$amount,'metadata[refund_request_id]'=>$requestId],$requestId);$pdo->prepare("UPDATE refund_requests SET status=IF(status='pending','submitted',status),stripe_refund_id=? WHERE id=?")->execute([$refund['id']??null,$requestId]);audit_admin($config,$admin['id'],'payment.refund','payment',$paymentId);json_response(['ok'=>true,'refund_request_id'=>$requestId]);}catch(Throwable $error){$pdo->prepare("UPDATE refund_requests SET status='failed',error_code=? WHERE id=? AND status IN ('pending','submitted')")->execute([substr($error->getMessage(),0,100),$requestId]);throw $error;}
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();$code=$error->getMessage();if(in_array($code,['PAYMENT_NOT_REFUNDABLE','REFUND_AMOUNT_INVALID'],true))json_error($code,'Payment cannot be refunded for that amount.',409);error_log('refund request failed: '.$error->getMessage());json_error('REFUND_FAILED','Refund could not be submitted.',502);}
